Update requirements.txt
changed to tenacity==8.0.1 resolve following error "AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?"